apps/resume/urls.py
"""Resume URLs."""

# Django
from django.urls import path

# Views
from apps.resume.views import TimelineListView, DownloadResumeView

urlpatterns = [
    path(
        route='',
        view=TimelineListView.as_view(),
        name='home'
    ),
    path(
        route='download/',
        view=DownloadResumeView.as_view(),
        name='download_resume'
    ),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path(
        'resume/',
        include(('apps.resume.urls', 'resume'), namespace='resume'),
    ),
    path(
        'portfolio/',
        include(('apps.portfolio.urls', 'portfolio'), namespace='portfolio'),
    ),
    path(
        'blog/',
        include(('apps.blog.urls', 'blog'), namespace='blog'),
    ),
    path(
        'contact/',
        include(('apps.contact.urls', 'contact'), namespace='contact')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> 
    <title>Denis Siavichay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <meta name="description" content="Denis Siavichay resume and portfolio" />
    <meta name="keywords" content="dbsiavichay, denis, siavichay, resume, portfolio" />
    <meta name="author" content="dbsiavichay" />
    <link rel="shortcut icon" href="/static/img/favicon.ico">


    {% include "base/css.html" %}
  </head>

  <body>
    <!-- Loading animation -->
    <div class="preloader">
      <div class="preloader-animation">
        <div class="preloader-spinner">
        </div>
      </div>
    </div>
    <!-- /Loading animation -->

    <div class="page">
      <div class="page-content">

          {% include "base/header.html" %}

          <!-- Mobile Navigation -->
          <div class="menu-toggle">
            <span></span>
            <span></span>
            <span></span>
          </div>
          <!-- End Mobile Navigation -->

          <!-- Arrows Nav -->
          <div class="lmpixels-arrows-nav">
            <div class="lmpixels-arrow-right"><i class="lnr lnr-chevron-right"></i></div>
            <div class="lmpixels-arrow-left"><i class="lnr lnr-chevron-left"></i></div>
          </div>
          <!-- End Arrows Nav -->

          <div class="content-area">
            <div class="animated-sections">
              {% block content %}{% endblock %}
            </div>
          </div>

      </div>
    </div>

    {% include "base/js.html" %}
  </body>
</html>

templates/base/css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/reset.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/animations.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/perfect-scrollbar.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">

<script src="{% static 'js/modernizr.custom.js' %}"></script>

templates/base/header.html
{% load static %}
<!-- Header -->
<header id="site_header" class="header mobile-menu-hide">
	<div class="header-content">
	  <div class="header-photo">
		<img src="{% static 'img/avatar.png' %}" alt="Denis Siavichay">
	  </div>
	  <div class="header-titles">
		<h2>Denis Siavichay</h2>
		<h4>Backend Developer</h4>
	  </div>
	</div>

	<ul class="main-menu">
	  <li class="active">
		<a href="#home" class="nav-anim">
		  <span class="menu-icon lnr lnr-home"></span>
		  <span class="link-text">Home</span>
		</a>
	  </li>
	  <li>
		<a href="#about-me" class="nav-anim">
		  <span class="menu-icon lnr lnr-user"></span>
		  <span class="link-text">About Me</span>
		</a>
	  </li>
	  <li>
		<a href="#resume" class="nav-anim">
		  <span class="menu-icon lnr lnr-graduation-hat"></span>
		  <span class="link-text">Resume</span>
		</a>
	  </li>
	  <li>
		<a href="#portfolio" class="nav-anim">
		  <span class="menu-icon lnr lnr-briefcase"></span>
		  <span class="link-text">Portfolio</span>
		</a>
	  </li>
	  <!--
	  <li>
		<a href="#blog" class="nav-anim">
		  <span class="menu-icon lnr lnr-book"></span>
		  <span class="link-text">Blog</span>
		</a>
	  </li>
	  -->
	  <li>
		<a href="#contact" class="nav-anim">
		  <span class="menu-icon lnr lnr-envelope"></span>
		  <span class="link-text">Contact</span>
		</a>
	  </li>
	</ul>

	<div class="social-links">
	  <ul>
		<li><a href="https://github.com/dbsiavichay" target="_blank"><i class="fab fa-github"></i></a></li>
		<li><a href="https://gitlab.com/dbsiavichay" target="_blank"><i class="fab fa-gitlab"></i></a></li>
		<li><a href="https://www.linkedin.com/in/dbsiavichay/" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
		<li><a href="https://twitter.com/dbsiavichay" target="_blank"><i class="fab fa-twitter"></i></a></li>
		<li><a href="https://www.facebook.com/dbsiavichay" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
		<li><a href="https://www.instagram.com/dbsiavichay/" target="_blank"><i class="fab fa-instagram"></i></a></li>
	  </ul>
	</div>

	<div class="header-buttons">
	  <a href="{% url 'resume:download_resume' %}" target="_blank" class="btn btn-primary">Download CV</a>
	</div>

	<div class="copyrights">© 2021 All rights reserved.</div>
  </header>
<!--End of Header -->

templates/base/js.html
{% load static %}

<script src="{% static 'js/jquery-2.1.3.min.js' %}"></script>
<script src="{% static 'js/modernizr.custom.js' %}"></script>
<script src="{% static 'js/animating.js' %}"></script>

<script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>

<script src="{% static 'js/perfect-scrollbar.min.js' %}"></script>
<script src="{% static 'js/jquery.shuffle.min.js' %}"></script>
<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

<script src="{% static 'js/validator.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>