apps/blog/urls.py
"""Blog URLs."""

# Django
from django.urls import path

# Views
from apps.blog.views import PostListView, PostDetailView

urlpatterns = [
    path(
        route='',
        view=PostListView.as_view(),
        name='home'
    ),
    path(
        route='post/<int:pk>/',
        view=PostDetailView.as_view(),
        name='post_detail'
    ),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path(
        'resume/',
        include(('apps.resume.urls', 'resume'), namespace='resume'),
    ),
    path(
        'portfolio/',
        include(('apps.portfolio.urls', 'portfolio'), namespace='portfolio'),
    ),
    path(
        'blog/',
        include(('apps.blog.urls', 'blog'), namespace='blog'),
    ),
    path(
        'contact/',
        include(('apps.contact.urls', 'contact'), namespace='contact')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
# Django
from django.db import models


class Media(models.Model):
    name = models.CharField(max_length=128, verbose_name='nombre')
    file = models.FileField(upload_to='files/%Y/%m/%d/')
    file_extension = models.CharField(max_length=32)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('date',)

    def __str__(self):
        return self.name


class Post(models.Model):
    DRAFT, PUBLISHED = 1, 2
    STATE_CHOICES = (('Borrador', DRAFT), ('Publicado', PUBLISHED))

    title = models.CharField(max_length=128, verbose_name='título')
    cover = models.ImageField(
        upload_to='posts/%Y/%m/%d/',
        blank=True,
        null=True,
        verbose_name='portada'
    )
    date = models.DateTimeField(auto_now_add=True, verbose_name='fecha')
    content = models.TextField(verbose_name='contenido')
    state = models.PositiveSmallIntegerField(
        choices=STATE_CHOICES,
        default=DRAFT
    )

    def __str__(self):
        return self.title

apps/blog/views.py
# Django
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView

# Models
from apps.blog.models import Post


class PostListView(ListView):
    model = Post


class PostDetailView(DetailView):
    model = Post

apps/blog/templates/blog/post_detail.html
{% extends "base/base.html" %}

{% load static markdownify %}

{% block metatitle %}Blog{% endblock %}

{% block header %}
{% include "base/header.html" with title="Post" description="Detalle de publicación" %}
{% endblock %}

{% block content %}
<div class="container padding4x">
    <div class="row">
        <div class="col-md-9">
            <div class="blog-posts">
                <article class="post-item">
                    <div class="entry-item" data-bg-image="{% static 'images/blog/img2.jpg' %}">
                        <img src="{% static 'images/8x5.png' %}" class="img-block" alt="image block">
                        <div class="entry-meta">
                            <div class="entry-date">
                                <span class="day">{{ post.date|date:"d" }}</span>
                                <span class="month">{{ post.date|date:"M" }}</span>
                            </div>
                            <div class="entry-title">
                                <div class="entry-author">Denis Siavichay</div>
                                <h1>
                                    {{ post.title }}
                                </h1>
                            </div>
                        </div>
                    </div>

                    <div class="blog-content">
                        <div class="meta-blocks">
                            <span>{{ post.date|date:"F d, Y" }}</span>
                            <span><i class="fa fa-dribbble"></i> Standard</span>
                            <span><i class="fa fa-comment"></i> 15 Comments</span>
                        </div>
                        
                        <div>
                            {{ post.content|markdown|safe }}
                        </div>


                        <div class="row footer-block">
                            <div class="col-md-6">
                                <div class="category-blocks">
                                    <a href="#">Work</a>
                                    <a href="#">Design</a>
                                    <a href="#">Story</a>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="share-blocks text-right">
                                    share this article
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-linkedin"></i></a>
                                    <a href="#"><i class="fa fa-google-plus"></i></a>
                                </div>
                            </div>
                        </div>

                    </div>

                    <div class="row blog-links">
                        <div class="col-sm-6">
                            <a href="#" class="link-prev">Previuos Post</a>
                        </div>
                        <div class="col-sm-6">
                            <a href="#" class="link-next">Next Post</a>
                        </div>
                    </div>

                </article>


                

                <div id="comments" class="comments-area">
                    <h2 class="comments-title">3 Comments</h2>
                    <ol class="comment-list">
                        <li>
                            <article>
                                <div class="comment-avatar">
                                    <img src="{% static 'images/blog/author.png' %}" class="avatar">
                                    <span class="comment-reply">
                                        <a class="comment-reply-link" href="#">Reply</a>
                                    </span>
                                </div>

                                <div class="comment-body">
                                    <div class="meta-data">
                                        <a href="#" class="comment-author">John doe</a>
                                        <span class="comment-date">
                                            FEB 9, 2014, AT 10:23
                                        </span>
                                    </div>
                                    <div class="comment-content">
                                        Dramatically re-engineer best-of-breed methods of empowerment without competitive synergy. Proactively enhance end-to-end initiatives and an expanded array of.
                                    </div>
                                </div>
                            </article>
                        </li>
                        <li>
                            <article>
                                <div class="comment-avatar">
                                    <img src="{% static 'images/blog/author.png' %}" class="avatar">
                                    <span class="comment-reply">
                                        <a class="comment-reply-link" href="#">Reply</a>
                                    </span>
                                </div>

                                <div class="comment-body">
                                    <div class="meta-data">
                                        <a href="#" class="comment-author">John doe</a>
                                        <span class="comment-date">
                                            FEB 9, 2014, AT 10:23
                                        </span>
                                    </div>
                                    <div class="comment-content">
                                        Dramatically re-engineer best-of-breed methods of empowerment without competitive synergy. Proactively enhance end-to-end initiatives and an expanded array of.
                                    </div>
                                </div>
                            </article>

                            <ol>
                                <li>
                                    <article>
                                        <div class="comment-avatar">
                                            <img src="{% static 'images/blog/author.png' %}" class="avatar">
                                            <span class="comment-reply">
                                                <a class="comment-reply-link" href="#">Reply</a>
                                            </span>
                                        </div>

                                        <div class="comment-body">
                                            <div class="meta-data">
                                                <a href="#" class="comment-author">John doe</a>
                                                <span class="comment-date">
                                                    FEB 9, 2014, AT 10:23
                                                </span>
                                            </div>
                                            <div class="comment-content">
                                                Dramatically re-engineer best-of-breed methods of empowerment without competitive synergy. Proactively enhance end-to-end initiatives and an expanded array of.
                                            </div>
                                        </div>
                                    </article>
                                </li>
                            </ol>
                        </li>
                        <li>
                            <article>
                                <div class="comment-avatar">
                                    <img src="{% static 'images/blog/author.png' %}" class="avatar">
                                    <span class="comment-reply">
                                        <a class="comment-reply-link" href="#">Reply</a>
                                    </span>
                                </div>

                                <div class="comment-body">
                                    <div class="meta-data">
                                        <a href="#" class="comment-author">John doe</a>
                                        <span class="comment-date">
                                            FEB 9, 2014, AT 10:23
                                        </span>
                                    </div>
                                    <div class="comment-content">
                                        Dramatically re-engineer best-of-breed methods of empowerment without competitive synergy. Proactively enhance end-to-end initiatives and an expanded array of.
                                    </div>
                                </div>
                            </article>
                        </li>
                    </ol>
                    <div id="respond" class="comment-respond">
                        <h3 id="reply-title" class="comment-reply-title">Leave a Comment</h3>
                        <form method="post" id="commentform" class="comment-form" novalidate="">
                            <p class="comment-form-author col-md-6">
                                <input id="author" name="author" type="text" value="" size="30" placeholder="Your name*">
                            </p>
                            <p class="comment-form-email col-md-6">
                                <input id="email" name="email" type="email" value="" size="30" placeholder="Your Email*">
                            </p>
                            <p class="comment-form-url">
                                <input id="url" name="url" type="url" value="" size="30" placeholder="Your website">
                            </p>
                            <p class="comment-form-comment">
                                <textarea id="comment" name="comment" placeholder="Comment"></textarea>
                            </p>
                            <p class="form-submit">
                                <input name="submit" type="submit" id="submit" class="submit" value="Post Comment"> <input type="hidden" name="comment_post_ID" value="1" id="comment_post_ID">
                            </p>					
                        </form>
                    </div>
                </div>

                

            </div>

        </div>
        
        <div class="col-md-3">

            <aside class="widget widget_search">
                <form action="/" method="get" class="search-form">
                    <input type="text" name="s" id="search" value="" placeholder="Search ..." />
                    <button type="submit"><i class="fa fa-search"></i></button>
                </form>
            </aside>

            <aside class="widget">
                <h5 class="widget-title">Categories</h5>
                <ul>
                    <li><a href="javascript:;"><span class="count">09</span> Design Mockups</a></li>
                    <li><a href="javascript:;"><span class="count">10</span> Websites</a></li>
                    <li><a href="javascript:;"><span class="count">07</span> Branding</a></li>
                    <li><a href="javascript:;"><span class="count">11</span> Motion Works</a></li>
                    <li><a href="javascript:;"><span class="count">13</span> Photoshop</a></li>
                    <li><a href="javascript:;"><span class="count">07</span> Wordpress</a></li>
                </ul>
            </aside>

            <aside class="widget">
                <h5 class="widget-title">Archives</h5>
                <ul>
                    <li><a href="javascript:;"><span class="count">10</span> June  2015</a></li>
                    <li><a href="javascript:;"><span class="count">11</span> May  2015</a></li>
                    <li><a href="javascript:;"><span class="count">08</span> April  2015</a></li>
                    <li><a href="javascript:;"><span class="count">10</span> March  2015</a></li>
                    <li><a href="javascript:;"><span class="count">14</span> February</a></li>
                    <li><a href="javascript:;"><span class="count">08</span> January</a></li>
                </ul>
            </aside>

            <aside class="widget">
                <h5 class="widget-title">Tags</h5>
                <div class="widget-tags">
                    <a href="javascript:;">Amazing</a>
                    <a href="javascript:;">Envato</a>
                    <a href="javascript:;">Themes</a>
                    <a href="javascript:;">Clean</a>
                    <a href="javascript:;">Responsiveness</a>
                    <a href="javascript:;">SEO</a>
                    <a href="javascript:;">Mobile</a>
                    <a href="javascript:;">iOS</a>
                    <a href="javascript:;">Flat</a>
                    <a href="javascript:;">Design</a>
                </div>
            </aside>

        </div>
        
    </div>
</div>
{% endblock %}

apps/blog/templates/blog/post_list.html
{% extends "base/base.html" %}

{% load static %}

{% block metatitle %}Blog{% endblock %}

{% block header %}
{% include "base/header.html" with title="Blog" description="Últimas publicaciones" %}
{% endblock %}

{% block content %}
<div class="container padding4x">
    <div class="row">
        <div class="col-md-12">
            <div class="blog-posts blog-grid">
                
                {% for post in object_list %}
                <article class="post-item col-md-4 col-sm-6 col-xs-12">
                    <div class="entry-item" data-bg-image="{% static 'images/blog/grid1.jpg' %}">
                        <img src="{% static 'images/1x1.png' %}" class="img-block" alt="image block">
                        <a href="{% url 'blog:post_detail' post.id %}" class="entry-hover at-link">
                            <span class="inner-table">
                                <span class="inner-cell">
                                    <span class="post-format"><i class="fa fa-image"></i></span>
                                </span>
                            </span>								
                        </a>
                        <div class="entry-meta">
                            <div class="entry-date">
                                <span class="day">{{ post.date|date:"d" }}</span>
                                <span class="month">{{ post.date|date:"M" }}</span>
                            </div>
                            <div class="entry-title">
                                <div class="entry-author">Denis Siavichay</div>
                                <h3>
                                    <a href="{% url 'blog:post_detail' post.id %}" class="at-link">
                                        {{ post.title }}
                                    </a>
                                </h3>
                            </div>
                        </div>
                    </div>
                </article>
                {% endfor %}


                                
                <p>&nbsp;</p>
                <ul class="pagination">
                    <li><span>1</span></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">Next</a></li>
                </ul>

            </div>

        </div>
        
    </div>
</div>
{% endblock %}