apps/resume/urls.py
"""Resume URLs."""

# Django
from django.urls import path

# Views
from apps.resume.views import TimelineListView, DownloadResumeView

urlpatterns = [
    path(
        route='',
        view=TimelineListView.as_view(),
        name='home'
    ),
    path(
        route='download/',
        view=DownloadResumeView.as_view(),
        name='download_resume'
    ),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path(
        'resume/',
        include(('apps.resume.urls', 'resume'), namespace='resume'),
    ),
    path(
        'portfolio/',
        include(('apps.portfolio.urls', 'portfolio'), namespace='portfolio'),
    ),
    path(
        'blog/',
        include(('apps.blog.urls', 'blog'), namespace='blog'),
    ),
    path(
        'contact/',
        include(('apps.contact.urls', 'contact'), namespace='contact')
    )
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/resume/models.py
# Django
from django.db import models
from django.core.validators import MaxValueValidator


class Timeline(models.Model):
    start_date = models.DateField(verbose_name='fecha de inicio')
    ends_date = models.DateField(
        blank=True,
        null=True,
        verbose_name='fecha de finalización'
    )

    class Meta:
        ordering = ('-start_date',)


class JobTitle(Timeline):
    level = models.CharField(
        max_length=64,
        verbose_name='nivel de instrucción'
    )
    institution = models.CharField(max_length=128, verbose_name='institución')
    name = models.CharField(
        max_length=128,
        verbose_name='título obtenido'
    )
    senescyt_number = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        verbose_name='registro senescyt'
    )

    class Meta:
        ordering = ('start_date',)
        verbose_name = 'título profesional'
        verbose_name_plural = 'títulos profesionales'

    def __str__(self):
        return f'{self.level} - {self.name}'


class JobExperience(Timeline):
    institution = models.CharField(max_length=128, verbose_name='institución')
    job_position = models.CharField(max_length=64, verbose_name='cargo/puesto')
    current_job = models.BooleanField(
        default=False,
        verbose_name='trabajo actual?'
    )

    class Meta:
        ordering = ('start_date',)
        verbose_name = 'experiencia profesional'
        verbose_name_plural = 'experiencias profesionales'

    def __str__(self):
        return f'{self.job_position} - {self.institution}'


class JobActivity(models.Model):
    description = models.TextField(verbose_name='descripción')
    experience = models.ForeignKey(JobExperience, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'actividad'
        verbose_name_plural = 'actividades'

    def __str__(self):
        return self.description


class Skill(models.Model):
    name = models.CharField(max_length=64, verbose_name='nombre')
    percent = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(limit_value=100)],
        verbose_name='pocentaje'
    )
    order = models.PositiveSmallIntegerField(default=1)

    class Meta:
        ordering = ('order',)

    def __str__(self):
        return self.name


class Knowledge(models.Model):
    name = models.CharField(max_length=64, verbose_name='nombre')
    order = models.PositiveSmallIntegerField(default=1)

    class Meta:
        verbose_name = 'conocimiento'
        ordering = ('order',)

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=64, verbose_name='nombre')
    percent = models.PositiveSmallIntegerField(
        validators=[MaxValueValidator(limit_value=100)],
        verbose_name='pocentaje'
    )
    order = models.PositiveSmallIntegerField(default=1)

    class Meta:
        verbose_name = 'idioma'
        ordering = ('order',)

    def __str__(self):
        return self.name

apps/resume/views.py
# Django
from django.urls import reverse_lazy
from django.views.generic import View, ListView
from django.http import HttpResponse
from django.conf import settings

# Models
from apps.resume.models import Timeline, Skill, Knowledge, Language


class TimelineListView(ListView):
    model = Timeline

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'skills': Skill.objects.all(),
            'knowledges': Knowledge.objects.all(),
            'languages': Language.objects.all()
        })
        return context


class DownloadResumeView(View):
    def get(self, request, *args, **kwargs):

        with open(settings.BASE_DIR + '/static/pdf/denis_resume.pdf', 'rb') as pdf:
            response = HttpResponse(pdf.read(), content_type="application/pdf")
            response['Content-Disposition'] = 'attachment; filename="resume.pdf"'

        pdf.close()
        return response

apps/resume/templates/resume/timeline_list.html
{% extends "base/base.html" %}

{% load static %}

{% block metatitle %}Resume{% endblock %}

{% block header %}
{% include "base/header.html" with title="Hoja de vida" description="Preparación y habilidades" %}
{% endblock %}

{% block content %}
<div class="container padding4x">
    <div class="row">
        <div class="col-md-12">
            
            <div class="timeline-exp">
                <div class="row">
                    <div class="col-xs-6">
                        <div class="exp-title">
                            <span class="exp-icon">
                                <i class="fa fa-graduation-cap"></i>
                            </span>
                            <h4>educación</h4>
                        </div>
                    </div>
                    <div class="col-xs-6">
                        <div class="exp-title">
                            <span class="exp-icon">
                                <i class="fa fa-briefcase"></i>
                            </span>
                            <h4>experiencia</h4>
                        </div>
                    </div>
                </div>

                <div class="timeline-wrapper">
                    {% for object in object_list %}
                    {% if object.jobexperience %}
                    <div class="row">
                        <div class="col-xs-6 tl-item pull-right">
                            <span class="icon">
                                <i class="fa fa-briefcase"></i>
                            </span>
                            <div class="caption">{{ object.start_date|date:"Y / M" }}  -  {{ object.ends_date|date:"Y / M"|default:"Actualmente" }}</div>
                            <h4>{{ object.jobexperience.job_position }}</h4>
                            <p>{{ object.jobexperience.institution }}</p>
                            <ul class="check-list">
                                {% for activity in object.jobexperience.jobactivity_set.all %}
                                <li>{{ activity.description }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    {% else %}
                    <div class="row">
                        <div class="col-xs-6 tl-item">
                            <span class="icon">
                                <i class="fa fa-graduation-cap"></i>
                            </span>
                            <div class="caption">{{ object.start_date|date:"Y / M" }}  -  {{ object.ends_date|date:"Y / M"|default:"Actualmente" }}</div>
                            <h4>{{ object.jobtitle.name }}</h4>
                            <p>{{ object.jobtitle.institution }}</p>
                            <p>{{ object.jobtitle.level }}</p>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}

                </div>

            </div>

        </div>
    </div>
</div>

<div data-bg-color="#2c292d">
<div class="container padding4x">
    <div class="row">
        <div class="col-md-12">
            <h2 class="title-md text-center">SKILLS PROFESIONALES</h2>
            <br>
        </div>
    </div>

    <div class="row">
        {% for skill in skills %}
        <div class="col-sm-6">
            <div class="progress-line">
                <div class="entry-title">
                    <h5>{{ skill.name }}</h5>
                    <span>{{ skill.percent }}%</span>
                </div>
                <div class="entry-line">
                    <div class="current"></div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
</div>

<div class="container padding4x">
    <div class="row">
        <div class="col-md-12">
            <p>&nbsp;</p>
            <h2 class="title-md text-center">HABILIDADES & CONOCIMIENTO</h2>
            <br>
        </div>
    </div>

    <ul class="row check-list">
        {% for knowledge in knowledges %}
        <li class="col-md-4 col-sm-6 col-xs-12">{{ knowledge.name }}</li>
        {% endfor %}
    </ul>
</div>

<div data-bg-color="#2c292d">
    <div class="container padding4x">
        <div class="row">
            <div class="col-md-12">
                <h2 class="title-md text-center">IDIOMAS</h2>
                <br>
            </div>
        </div>

        <div class="row">
            {% for language in languages %}
            <div class="{% if forloop.counter == 1 %}col-md-offset-3{% endif %} col-md-2 col-sm-4 col-xs-4">
                <div class="pie-progress-wrapper">
                    <div class="pie_progress" role="progressbar" data-goal="{{ language.percent }}">
                        <div class="pie_progress__number">0%</div>
                    </div>
                    <h4>{{ language.name }}</h4>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>
</div>

<div class="container padding4x">
    <div class="row">
        <div class="col-md-12">
            <h2 class="title-md text-center">HOBBIES PERSONALES</h2>
            <br>
        </div>
    </div>

    <div class="row icon-boxes">
        <div class="box-item col-sm-offset-3 col-sm-2">
            <div class="entry-item">
                <img src="{% static 'images/1x1.png' %}" class="image-block" alt="image sizer">
                <span style="background-image:url(/static/images/pages/resume/bbq.png);"></span>
            </div>
            <div class="entry-hover">
                <h6>Parrillar</h6>
                <p>Asar y ahumar, probar diferentes cortes de carnes en varias preparaciones.</p>
            </div>
        </div>

        <div class="box-item col-sm-2">
            <div class="entry-item">
                <img src="{% static 'images/1x1.png' %}" class="image-block" alt="image sizer">
                <span style="background-image:url(/static/images/pages/resume/microphone.png);"></span>
            </div>
            <div class="entry-hover">
                <h6>Cantar</h6>
                <p>A veces asisto a karaokes con familiares y amigos donde practico el canto.</p>
            </div>
        </div>

        <div class="box-item col-sm-2">
            <div class="entry-item">
                <img src="{% static 'images/1x1.png' %}" class="image-block" alt="image sizer">
                <span style="background-image:url(/static/images/pages/resume/traveler.png);"></span>
            </div>
            <div class="entry-hover">
                <h6>Viajar</h6>
                <p>Conocer varios lugares y gente nueva, adquirir experiencias de vida.</p>
            </div>
        </div>
        <div class="clearfix"></div>

    </div>
</div>
{% endblock %}